# Generated by Django 2.2.5 on 2019-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
