# Generated by Django 2.2.5 on 2019-10-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191001_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='cover',
            field=models.ImageField(null=True, upload_to='files/covers'),
        ),
    ]
