# Generated by Django 2.2.5 on 2019-10-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vastfallbackconfig',
            old_name='vast_xml',
            new_name='ad_tags',
        ),
    ]
