# Generated by Django 2.2.5 on 2019-10-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0002_auto_20191001_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmapelement',
            old_name='vmap_xml',
            new_name='ad_tag',
        ),
        migrations.AlterField(
            model_name='vmapelement',
            name='type',
            field=models.CharField(choices=[('preroll', 'preroll'), ('midroll', 'midroll'), ('postroll', 'postroll')], max_length=128),
        ),
    ]
