# Generated by Django 2.2.5 on 2019-10-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0003_auto_20191001_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmapelement',
            name='waterfall_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads_manager.VastFallbackConfig'),
        ),
    ]
