# Generated by Django 2.2.5 on 2019-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0004_vmapelement_waterfall_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmapelement',
            name='ad_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
