# Generated by Django 2.2.5 on 2019-10-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0005_auto_20191001_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmapelement',
            name='time_offset',
            field=models.CharField(choices=[('start', 'start'), ('00:00:15.000', '15 sec'), ('00:00:30.000', '30 sec'), ('end', 'end')], default='start', max_length=128),
        ),
    ]
